# Container Image for test_CPU_parallel.py
# A basic CPU workload generator
# See https://github.com/LucaCanali/Miscellaneous/tree/master/Performance_Testing/Test_CPU_parallel_Python

FROM python:3.13.1-alpine3.21

# The main goal of this container is to be used for running test_CPU_parallel.py
RUN pip install test_CPU_parallel

