apiVersion: v1
kind: Pod
metadata:
  name: test-cpu-pod
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: lucacanali/test_cpu_parallel.py:py3.11
    args:
      - "test_CPU_parallel.py"
      - "-w"
      - "2"
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "2"

