# Container Image for test_cpu_parallel
# A basic CPU workload generator
# See https://github.com/LucaCanali/Miscellaneous/tree/master/Performance_Testing/Test_CPU_parallel_Rust

FROM ubuntu:22.04

# The main goal of this container is to be used for running /opt/test_cpu_parallel
COPY test_cpu_parallel /opt/test_cpu_parallel

WORKDIR /opt

