apiVersion: v1
kind: Pod
metadata:
  name: test-cpu-pod
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: lucacanali/test_cpu_parallel
    command:
      - "/opt/test_cpu_parallel"
      - "-w"
      - "2"
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "2"

