{
 "title": "Spark_Perf_Dashboard_v01",
 "time": { "from": "now", "to": "now-5m" },
 "templating": {
  "list": [
   {
    "name": "UserName",
    "label": "User",
    "query": "SHOW TAG VALUES WITH KEY = \"username\""
   },
   {
    "name": "ApplicationId",
    "label": "Spark Application Id",
    "query": "SHOW TAG VALUES WITH KEY = \"applicationid\" WHERE \"username\" =~ /$UserName/ "
   }
  ]
 },
 "panels": [
  { "title": "Summary metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "N# of Active Tasks - latest value",
   "type": "singlestat",
   "description": "Latest sample of the value of number of active tasks, summed over all executors active in the selected time filter interval.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.runningStages",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"threadpool.activeTasks\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Executor CPU time",
   "type": "singlestat",
   "description": "Total executor CPU time computed from from executor metrics. Displays CPU time used by all the executors' JVMs active in the selected time filter interval. It contains CPU time used for tasks and other activities in the JVM, notably garbage collection. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jvmCpuTime",
     "query": "select sum(lastvalperprocess) from ( SELECT process, last(value) as lastvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Task CPU Usage ",
   "type": "singlestat",
   "description": "Total task CPU usage from task metrics. Displays CPU time used for all the completed tasks, from the task metrics data source. Note, values from executors that are no more active in the selected time window are not counted.\n",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Task GC Time ",
   "type": "singlestat",
   "description": "Total time spent in GC operations during task execution. Displays values for all the completed tasks, from the task metrics data source. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Spark 3.0 appSource: Tasks killed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "tasks.completedTasks.count",
     "query": "SELECT last(\"value\") FROM \"tasks.killedTasks.count\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.failedStages",
     "query": "SELECT last(\"value\") FROM \"stage.failedStages\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap memory Used (% of maximum usable)",
   "type": "singlestat",
   "description": "JVM metric from MemoryMXBean. Latest value of the % of heap memory used, averaging over executors and driver.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heap.usage",
     "query": "select mean(lastvalperprocess)*100 from  (SELECT process, last(value) as lastvalperprocess FROM \"heap.usage\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS Bytes Read",
   "type": "singlestat",
   "description": "Bytes read from HDFS. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess  FROM \"filesystem.hdfs.read_bytes\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS Bytes Written",
   "type": "singlestat",
   "description": "Bytes written to HDFS. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess  FROM \"filesystem.hdfs.write_bytes\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "N# of Completed Tasks",
   "type": "singlestat",
   "description": "Number of completed tasks, from JVM threadpool metrics. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "threadpool.completeTasks",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"threadpool.completeTasks\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Spark 3.0: Succeeded Jobs Count",
   "type": "singlestat",
   "description": "Number of succeeded jobs, from the appsource metric introduced in Spark 3.0",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jobs.succeededJobs.count",
     "query": "SELECT value FROM \"jobs.succeededJobs.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "Spark workload metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of Active Tasks",
   "type": "graph",
   "description": "Number of active tasks per executor\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "N# Active Tasks" }
   ],
   "targets": [
    {
     "alias": "N# active tasks - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT value FROM \"threadpool.activeTasks\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executors JVM CPU Utilization (N# cores-equivalent)",
   "type": "graph",
   "description": "Total executor CPU utilization computed from executors' metrics. The value is normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would give an equivalent value of CPU utilization.\n",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    {
     "format": "short",
     "label": "CPU Utilization (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "JVM CPU - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "jvmCpuTime",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  / 1000000000 FROM \"jvmCpuTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time (N# of cores equivalent) - from task metrics",
   "type": "graph",
   "description": "Time the JVM process has spent in garbage collection. The value is normalized in \"N# of core equivalent\", that is the hypothetical number of cores working at 100% on GC that would give an equivalent result.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "GC Time (N# cores equivalent)" }
   ],
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  / 1000 FROM  \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Task CPU Utilization (N# cores equivalent) -  from Task metrics",
   "type": "graph",
   "description": "Total task CPU utilization computed from task metrics. The value is normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would give an equivalent value of CPU utilization.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    {
     "format": "short",
     "label": "CPU Utilization (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "Task CPU - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "cpuTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  / 1000000000 FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executor run time and wait time components",
   "type": "graph",
   "description": "Executor run time and wait time components compared. The run time spent by Spark executors is aggregated per area of activity. The difference between run time and wait time measurements can be interpreted as due to missing instrumentation (e.g. HDFS/filesystem I/O wait time). The values are normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would yield an equivalent value for the given metric.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    {
     "format": "none",
     "label": "Time component (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "deserializeCpuTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "deserializeCpuTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"deserializeCpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "deserializeTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "deserializeTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"deserializeTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "cpuTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpuTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "shuffleWriteTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleWriteTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"shuffleWriteTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "resultSerializationTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "resultSerializationTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"resultSerializationTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "shuffleFetchWaitTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleFetchWaitTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"shuffleFetchWaitTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "jvmGCTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "runTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run Time - from task metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    {
     "format": "none",
     "label": "Task Run Time (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "run time - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s) / 1000  FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of completed tasks per executor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "N# of completed tasks" }
   ],
   "targets": [
    {
     "alias": "Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "threadpool.completeTasks",
     "query": "SELECT last(\"value\") FROM \"threadpool.completeTasks\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter GROUP BY \"process\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Write Time - from task metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    {
     "format": "none",
     "label": "Shuffle Write Time (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "shuffle write time - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s) / 1000000000  FROM \"shuffleWriteTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "JVM and Spark memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Executor JVM Total Memory Used",
   "type": "graph",
   "description": "Total memory (heap + non-heap) used per executor.  From MemoryMXBean.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes", "label": "JVM total memory used" }
   ],
   "targets": [
    {
     "alias": "Total Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT value FROM \"total.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process != 'driver'  GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Executor JVM Heap Memory Used",
   "type": "graph",
   "description": "Heap memory used per executor.  From MemoryMXBean.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bytes", "label": "JVM heap memory used" }
   ],
   "targets": [
    {
     "alias": "Heap Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT value FROM \"heap.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process != 'driver' GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Driver JVM Total Memory Used",
   "type": "graph",
   "description": "Total memory (heap + non-heap) used by the driver.  From MemoryMXBean.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bytes", "label": "JVM total memory used" }
   ],
   "targets": [
    {
     "alias": "Total Memory  Used - $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT value FROM \"total.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process = 'driver' GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Block Manager: memory and disk used",
   "type": "graph",
   "description": "Storage memory and disk used by the block manager.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    {
     "format": "decmbytes",
     "label": "Block manager memory and disk used"
    }
   ],
   "targets": [
    {
     "alias": "heap Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT value FROM \"memory.onHeapMemUsed_MB\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    },
    {
     "alias": "non-heap Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"memory.offHeapMemUsed_MB\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Disk used - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"disk.diskSpaceUsed_MB\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Spark I/O metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "HDFS bytes read/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps", "label": "HDFS bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "hdfs bytes read - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"filesystem.hdfs.read_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS bytes written/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "Bps", "label": "HDFS bytes written/sec" }
   ],
   "targets": [
    {
     "alias": "hdfs bytes read - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"filesystem.hdfs.write_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Total Bytes Read/sec - from task metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle total bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "shuffle Total Bytes Read - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleTotalBytesRead.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"shuffleTotalBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written/sec - from taskmetrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle bytes written/sec" }
   ],
   "targets": [
    {
     "alias": "shuffleBytesWritten - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleBytesWritten.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"shuffleBytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Read Composition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "shuffleRemoteBytesRead",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleRemoteBytesRead.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) as perprocessval FROM \"shuffleRemoteBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    },
    {
     "alias": "shuffleLocalBytesRead",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleLocalBytesRead.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) as perprocessval FROM \"shuffleLocalBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval),  \"process\") GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  }
 ]
}