{
 "title": "Spark_Perf_Dashboard_v04_PromQL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "UserName", "label": "User", "query": { "query": "label_values(username)" } },
   {
    "name": "ApplicationId",
    "label": "Spark Application Id",
    "query": {
     "query": "label_values({username=~\"$UserName\"}, applicationid)"
    }
   },
   { "name": "AggrInterval", "label": "Task metrics time average", "query": "2s, 10s, 20s, 30s, 1m, 2m, 5m" }
  ]
 },
 "panels": [
  { "title": "Summary metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Run Time",
   "type": "stat",
   "description": "Total task Run Time from task metrics in the selected time range. \n",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(runTime_count_value{applicationid=\"$ApplicationId\"}[$__range]) \r\n  - \r\n  min_over_time(runTime_count_value{applicationid=\"$ApplicationId\"}[$__range])\r\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) - sum(firstvalperprocess) from \n(SELECT process, last(value) as lastvalperprocess FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n(SELECT process, first(value) as firstvalperprocess FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executors CPU time",
   "type": "stat",
   "description": "Executor CPU time computed from executor metrics for the selected time range. Displays CPU time used by all the executors' JVMs active in the selected time filter interval. It contains CPU time used for executing tasks and for other activities in the JVM, notably garbage collection. Note, values from executors that are no more active in the selected time window are not accounted for.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(jvmCpuTime_value{applicationid=\"$ApplicationId\", executorid!=\"driver\"}[$__range]) \r\n  - \r\n  min_over_time(jvmCpuTime_value{applicationid=\"$ApplicationId\", executorid!=\"driver\"}[$__range])\r\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jvmCpuTime",
     "query": "select sum(lastvalperprocess) - sum(firstvalperprocess) from \n( SELECT process, last(value) as lastvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n( SELECT process, first(value) as firstvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Driver CPU time",
   "type": "stat",
   "description": "Driver CPU time computed from executor metrics for the selected time range. ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(jvmCpuTime_value{applicationid=\"$ApplicationId\", executorid=\"driver\"}[$__range]) \r\n  - \r\n  min_over_time(jvmCpuTime_value{applicationid=\"$ApplicationId\", executorid=\"driver\"}[$__range])\r\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jvmCpuTime",
     "query": "select sum(lastvalperprocess) - sum(firstvalperprocess) from \n( SELECT process, last(value) as lastvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n( SELECT process, first(value) as firstvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Task CPU Usage ",
   "type": "stat",
   "description": "Total task CPU usage from task metrics in the selected time range. Displays CPU time used for all the completed tasks, from the task metrics data source. Note, values from executors that are no more active in the selected time window are not counted.\n",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(cpuTime_count_value{applicationid=\"$ApplicationId\"}[$__range]) \r\n  - \r\n  min_over_time(cpuTime_count_value{applicationid=\"$ApplicationId\"}[$__range])\r\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) - sum(firstvalperprocess) from \n(SELECT process, last(value) as lastvalperprocess FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n(SELECT process, first(value) as firstvalperprocess FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Task GC Time ",
   "type": "stat",
   "description": "Total time spent in GC operations during task execution for the selected time range. Displays values for all the completed tasks, from the task metrics data source. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(jvmGCTime_count_value{applicationid=\"$ApplicationId\"}[$__range]) \r\n  - \r\n  min_over_time(jvmGCTime_count_value{applicationid=\"$ApplicationId\"}[$__range])\r\n)\r\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "job.activeJobs",
     "query": "select sum(lastperprocessval) - sum(firstperprocessval) from \n(SELECT process, last(\"value\") as lastperprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n(SELECT process, first(\"value\") as firstperprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "N# of Tasks, Compled",
   "type": "stat",
   "description": "Number of completed tasks, from JVM threadpool metrics in the selected time range. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(threadpool_completeTasks_value{applicationid=\"$ApplicationId\"}[$__range]) \r\n  - \r\n  min_over_time(threadpool_completeTasks_value{applicationid=\"$ApplicationId\"}[$__range])\r\n)",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "threadpool.completeTasks",
     "query": "select sum(lastperprocessval) - sum(firstperprocessval) from \n(SELECT process, last(\"value\") as lastperprocessval FROM \"threadpool.completeTasks\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n(SELECT process, first(\"value\") as firstperprocessval FROM \"threadpool.completeTasks\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Memory Used (% of maximum usable)",
   "type": "gauge",
   "description": "Latest value of the % of heap memory used, averaging over executors and driver. JVM metric from MemoryMXBean. Conditional to spark.metrics.conf.*.source.jvm.class=org.apache.spark.metrics.source.JvmSource",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(heap_usage_value{applicationid=\"$ApplicationId\"}[$__range]) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "heap.usage",
     "query": "select mean(lastvalperprocess)*100 from  (SELECT process, last(value) as lastvalperprocess FROM \"heap.usage\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "description": "Total number of bytes read from task metrics in the selected time range. \n",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(bytesRead_count_value{applicationid=\"$ApplicationId\"}[$__range]) \r\n  - \r\n  min_over_time(bytesRead_count_value{applicationid=\"$ApplicationId\"}[$__range])\r\n)\r\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) - sum(firstvalperprocess) from \n(SELECT process, last(value) as lastvalperprocess FROM \"bytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n(SELECT process, first(value) as firstvalperprocess FROM \"bytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "description": "Total number of bytes written from task metrics in the selected time range. \n",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(bytesWritten_count_value{applicationid=\"$ApplicationId\"}[$__range]) \r\n  - \r\n  min_over_time(bytesWritten_count_value{applicationid=\"$ApplicationId\"}[$__range])\r\n)\r\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) - sum(firstvalperprocess) from \n(SELECT process, last(value) as lastvalperprocess FROM \"bytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n(SELECT process, first(value) as firstvalperprocess FROM \"bytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "stat",
   "description": "Total number of shuffle bytes written from task metrics in the selected time range. \n",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(shuffleBytesWritten_count_value{applicationid=\"$ApplicationId\"}[$__range]) \r\n  - \r\n  min_over_time(shuffleBytesWritten_count_value{applicationid=\"$ApplicationId\"}[$__range])\r\n)\r\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) - sum(firstvalperprocess) from \n(SELECT process, last(value) as lastvalperprocess FROM \"shuffleBytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process),\n(SELECT process, first(value) as firstvalperprocess FROM \"shuffleBytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "N# of Failed Tasks",
   "type": "stat",
   "description": "Failed tasks for the appStatus metrics. Conditional to spark.metrics.appStatusSource.enabled=true (default is false)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tasks_failedTasks_count_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "tasks.completedTasks.count",
     "query": "SELECT \"value\" FROM \"tasks.failedTasks.count\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "stat",
   "description": "Number of failed stages from the appStatus \n metrics.\nConditional to a configuration parameter:\nspark.metrics.appStatusSource.enabled=true (default is false)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stages_failedStages_count_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "stage.failedStages",
     "query": "SELECT \"value\" FROM \"stages.failedStages.count\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Current N# of Active Tasks - latest value",
   "type": "stat",
   "description": "Latest sample of the value of number of active tasks, summed over all executors",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(threadpool_activeTasks_value{applicationid=\"$ApplicationId\"})",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "stage.runningStages",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"threadpool.activeTasks\" WHERE \"applicationid\" = '$ApplicationId' and time > now() - 60s GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Average N# of Active Tasks - mean value",
   "type": "stat",
   "description": "Average value of number of active tasks",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(threadpool_activeTasks_value{applicationid=\"$ApplicationId\"}[$__range]))",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "stage.runningStages",
     "query": "select sum(perprocessval) from (SELECT mean(\"value\") as perprocessval FROM \"threadpool.activeTasks\" WHERE $timeFilter and \"applicationid\" = '$ApplicationId' GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Current N# of Running Stages - latest value",
   "type": "stat",
   "description": "Number of running stages from the DAG scheduler.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "stage_runningStages_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "stage.failedStages",
     "query": "SELECT \"value\" FROM \"stage.runningStages\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Succeeded Jobs Count",
   "type": "stat",
   "description": "Number of succeeded jobs, from the appStatus metric (introduced in Spark 3.0). Conditional to spark.metrics.appStatusSource.enabled=true (default is false)",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_succeededJobs_count_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jobs.succeededJobs.count",
     "query": "SELECT value FROM \"jobs.succeededJobs.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total - N# of Tasks, Completed ",
   "type": "stat",
   "description": "Number of completed tasks, from JVM threadpool metrics since the start of the Spark application.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(threadpool_completeTasks_value{applicationid=\"$ApplicationId\"}[10d]) \r\n  - \r\n  min_over_time(threadpool_completeTasks_value{applicationid=\"$ApplicationId\"}[10d])\r\n)",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "threadpool.completeTasks",
     "query": "select sum(lastperprocessval) from \n(SELECT process, last(\"value\") as lastperprocessval FROM \"threadpool.completeTasks\" WHERE \"applicationid\" = '$ApplicationId' GROUP BY process)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total - CPU Time, Executors",
   "type": "stat",
   "description": "Total executor CPU time, from executor metrics since the start of the Spark application. Displays CPU time used by all the executors' JVMs for the duration of the application. It contains CPU time used for executing tasks and for other activities in the JVM, notably garbage collection.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  max_over_time(jvmCpuTime_value{applicationid=\"$ApplicationId\", executorid!=\"driver\"}[10d]) \r\n  - \r\n  min_over_time(jvmCpuTime_value{applicationid=\"$ApplicationId\", executorid!=\"driver\"}[10d])\r\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jvmCpuTime",
     "query": "select sum(lastvalperprocess) as JCMCPU from ( SELECT process, last(value) as lastvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "Spark workload metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number of Active Tasks",
   "type": "timeseries",
   "description": "Number of active tasks per executor.\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "N# active tasks - Executor $tag_process",
     "expr": "avg_over_time(threadpool_activeTasks_value{applicationid=\"$ApplicationId\"}[$AggrInterval])",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"threadpool.activeTasks\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executors JVM CPU Utilization (N# cores-equivalent)",
   "type": "timeseries",
   "description": "Total executor CPU utilization computed from executors' JVM instrumentation. The value is normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would give an equivalent value of CPU utilization.\n",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "JVM CPU - Executor $tag_process",
     "expr": "rate(jvmCpuTime_value{applicationid=\"$ApplicationId\"}[$AggrInterval]) / 1000000000",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "jvmCpuTime",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000000000 FROM \"jvmCpuTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executor run time and wait time components",
   "type": "timeseries",
   "description": "Executor run time and wait time components compared. The run time spent by Spark executors is aggregated per area of activity. The difference between run time measurements and wait time measurements can be interpreted as due to time not instrumented (e.g. HDFS/filesystem I/O wait time). The values are normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would yield an equivalent value for the given metric.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "deserializeCpuTime",
     "expr": "sum(rate(cpuTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])) / 1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "CPU time",
     "measurement": "deserializeCpuTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"deserializeCpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "deserializeTime",
     "expr": "sum(rate(jvmGCTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])) / 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "GC time",
     "measurement": "deserializeTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"deserializeTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "cpuTime",
     "expr": "sum(rate(shuffleWriteTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])) / 1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Shuffle write time",
     "measurement": "cpuTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "shuffleWriteTime",
     "expr": "sum(rate(resultSerializationTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])) / 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Result serialization time",
     "measurement": "shuffleWriteTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"shuffleWriteTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "resultSerializationTime",
     "expr": "sum(rate(shuffleFetchWaitTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])) / 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Shuffle fetch wait time",
     "measurement": "resultSerializationTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"resultSerializationTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "jvmGCTime",
     "expr": "sum(rate(deserializeTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])) / 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deserialize time",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "runTime",
     "expr": "sum(rate(runTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])) / 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Run time",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Run Time - from task metrics",
   "type": "timeseries",
   "description": "Time the Executor has spent running tasks, including idle time and wait time (for I/O or other event). The value is normalized in \"N# of core equivalent\", that is the hypothetical number of cores working at 100% running tasks that would give an equivalent result.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "run time - Executor $tag_process",
     "expr": "rate(runTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval]) / 1000",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s) / 1000  FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time (N# of cores equivalent) - from task metrics",
   "type": "timeseries",
   "description": "Time the JVM process has spent in garbage collection. The value is normalized in \"N# of core equivalent\", that is the hypothetical number of cores working at 100% on GC that would give an equivalent result.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "expr": "rate(jvmGCTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval]) / 1000",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000 FROM  \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval),process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Task CPU Utilization (N# cores equivalent) -  from Task metrics",
   "type": "timeseries",
   "description": "Total task CPU utilization computed from task metrics. The value is normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would give an equivalent value of CPU utilization.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Task CPU - Executor $tag_process",
     "expr": "rate(cpuTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval]) / 1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "cpuTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000000000 FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Write Time - from task metrics",
   "type": "timeseries",
   "description": "Time the Executor has spent writing shuffle data. The value is normalized in \"N# of core equivalent\", that is the hypothetical number of cores working at 100% on shuffle writing that would give an equivalent result.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "shuffle write time - Executor $tag_process",
     "expr": "rate(shuffleWriteTime_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval]) / 1000000000\r\n",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s) / 1000000000  FROM \"shuffleWriteTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "Spark Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "JVM On Heap Memory",
   "type": "timeseries",
   "description": "JVM Heap Memory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "JVM heap memory - Executor $tag_process",
     "expr": "JVMHeapMemory_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"JVMHeapMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Off Heap Memory",
   "type": "timeseries",
   "description": "JVM Off Heap Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "JVM off heap memory - Executor $tag_process",
     "expr": "JVMOffHeapMemory_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"JVMOffHeapMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OnHeapUnifiedMemory",
   "type": "timeseries",
   "description": "OnHeapUnifiedMemory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "OnHeapUnifiedMemory - Executor $tag_process",
     "expr": "OnHeapUnifiedMemory_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OnHeapUnifiedMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OffHeapUnifiedMemory",
   "type": "timeseries",
   "description": "OffHeapUnifiedMemory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "OffHeapUnifiedMemory - Executor $tag_process",
     "expr": "OffHeapUnifiedMemory_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OffHeapUnifiedMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OnHeap Execution Memory",
   "type": "timeseries",
   "description": "OnHeapExecutionMemory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "OnHeapExecutionMemory - Executor $tag_process",
     "expr": "OnHeapExecutionMemory_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OnHeapExecutionMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OnHeap Storage Memory",
   "type": "timeseries",
   "description": "OnHeap Storage Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "OnHeapStorageMemory - Executor $tag_process",
     "expr": "OnHeapStorageMemory_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OnHeapStorageMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "MinorGCTime",
   "type": "timeseries",
   "description": "MinorGCTime",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "expr": "rate(MinorGCTime_value{applicationid=\"$ApplicationId\"}[$AggrInterval]) / 1000",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000 FROM  \"MinorGCTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "MajorGCTime",
   "type": "timeseries",
   "description": "MajorGCTime",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "expr": "rate(MajorGCTime_value{applicationid=\"$ApplicationId\"}[$AggrInterval]) / 1000",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000 FROM  \"MajorGCTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "ProcessTreeJVMRSSMemory",
   "type": "timeseries",
   "description": "ProcessTreeJVMRSSMemory. Conditional to --conf spark.executor.processTreeMetrics.enabled=true",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "JMV RSS - Executor $tag_process",
     "expr": "ProcessTreeJVMRSSMemory_value{applicationid=\"$ApplicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"ProcessTreeJVMRSSMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "ProcessTreePythonRSSMemory",
   "type": "timeseries",
   "description": "ProcessTreePythonRSSMemory. Conditional to --conf spark.executor.processTreeMetrics.enabled=true",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Python RSS - Executor $tag_process",
     "expr": "rate(ProcessTreePythonRSSMemory_value{applicationid=\"$ApplicationId\"}[$AggrInterval])",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"ProcessTreePythonRSSMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM source  memory metrics (conditional to spark.metrics.conf.*.source.jvm.class=org.apache.spark.metrics.source.JvmSource)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 }
  },
  {
   "title": "Executor JVM Total Memory Used",
   "type": "timeseries",
   "description": "Total memory (heap + non-heap) used per executor.  From MemoryMXBean.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total Memory  Used - Executor $tag_process",
     "expr": "total_used_value{applicationid=\"$ApplicationId\", executorid!=\"driver\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "heap.used",
     "query": "SELECT mean(value) FROM \"total.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process != 'driver'  GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Executor JVM Heap Memory Used",
   "type": "timeseries",
   "description": "Heap memory used per executor.  From MemoryMXBean.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Heap Memory  Used - Executor $tag_process",
     "expr": "heap_used_value{applicationid=\"$ApplicationId\", executorid!=\"driver\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "heap.used",
     "query": "SELECT mean(value) FROM \"heap.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process != 'driver' GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Driver JVM Total Memory Used",
   "type": "timeseries",
   "description": "Total memory (heap + non-heap) used by the driver.  From MemoryMXBean.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total Memory  Used - $tag_process",
     "expr": "total_used_value{applicationid=\"$ApplicationId\", executorid=\"driver\"}",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "Total used memory, {{executorid}}",
     "measurement": "heap.used",
     "query": "SELECT mean(value) FROM \"total.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process = 'driver' GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Driver JVM CPU Utilization (N# cores-equivalent)",
   "type": "timeseries",
   "description": "Driver CPU utilization computed from the JVM instrumentation. The value is normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would give an equivalent value of CPU utilization.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "JVM CPU - Executor $tag_process",
     "expr": "rate(jvmCpuTime_value{applicationid=\"$ApplicationId\", executorid=\"driver\"}[$AggrInterval]) / 1000000000",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "JVM CPU time, {{executorid}}",
     "measurement": "jvmCpuTime",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000000000 FROM \"jvmCpuTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "Spark I/O metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "HDFS bytes read/sec",
   "type": "timeseries",
   "description": "HDFS read throughput.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "hdfs bytes read - Executor $tag_process",
     "expr": "rate(filesystem_hdfs_read_bytes_value{applicationid=\"$ApplicationId\"}[$AggrInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"filesystem.hdfs.read_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS bytes written/sec",
   "type": "timeseries",
   "description": "HDFS write throughput.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "hdfs bytes written - Executor $tag_process",
     "expr": "rate(filesystem_hdfs_write_bytes_value{applicationid=\"$ApplicationId\"}[$AggrInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"filesystem.hdfs.write_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Total Bytes Read/sec - from task metrics",
   "type": "timeseries",
   "description": "Shuffle read throughput.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "shuffle Total Bytes Read - Executor $tag_process",
     "expr": "rate(shuffleTotalBytesRead_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "shuffleTotalBytesRead.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"shuffleTotalBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($groupbyInterval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written/sec - from taskmetrics",
   "type": "timeseries",
   "description": "Shuffle write throughput.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "shuffleBytesWritten - Executor $tag_process",
     "expr": "rate(shuffleBytesWritten_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "shuffleBytesWritten.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"shuffleBytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($groupbyInterval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Read Composition",
   "type": "timeseries",
   "description": "Details of shuffle I/O operations, local and remote.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "shuffleRemoteBytesRead",
     "expr": "sum(rate(shuffleLocalBytesRead_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Shuffle local bytes read",
     "measurement": "shuffleRemoteBytesRead.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) as perprocessval FROM \"shuffleRemoteBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval), process) GROUP BY time($groupbyInterval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    },
    {
     "alias": "shuffleLocalBytesRead",
     "expr": "sum(rate(shuffleRemoteBytesRead_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Shuffle Remote bytes read",
     "measurement": "shuffleLocalBytesRead.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) as perprocessval FROM \"shuffleLocalBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($groupbyInterval),  \"process\") GROUP BY time($groupbyInterval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes spilled to disk per sec - from taskmetrics",
   "type": "timeseries",
   "description": "Bytes spilled to disk per second",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "diskBytesSpilled - Executor $tag_process",
     "expr": "rate(diskBytesSpilled_count_value{applicationid=\"$ApplicationId\"}[$AggrInterval])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "exec: {{executorid}}",
     "measurement": "shuffleBytesWritten.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"diskBytesSpilled.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($groupbyInterval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  }
 ]
}